from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
from pprint import pformat


ROOT = Path(__file__).resolve().parents[1]
PACKAGE_DIR = ROOT / "marketing_diagnosis"
BUNDLE_PATH = PACKAGE_DIR / "_versioned_runtime.py"
LATEST_PATH = PACKAGE_DIR / "latest.py"
MANIFEST_PATH = ROOT / "docs" / "versioned-module-consolidation.md"
INIT_PATH = PACKAGE_DIR / "__init__.py"
MAIN_PATH = PACKAGE_DIR / "main.py"

VERSIONED_FILE_RE = re.compile(r"^.+_v\d+(?:_legacy)?\.py$")
INIT_MARKER_START = "# BEGIN VERSIONED MODULE RUNTIME"
INIT_MARKER_END = "# END VERSIONED MODULE RUNTIME"


def versioned_files() -> list[Path]:
    return sorted(
        path
        for path in PACKAGE_DIR.glob("*.py")
        if VERSIONED_FILE_RE.fullmatch(path.name)
    )


def module_name(path: Path) -> str:
    return f"marketing_diagnosis.{path.stem}"


def digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def build_bundle(sources: dict[str, str], filenames: dict[str, str]) -> str:
    source_literal = pformat(sources, width=120, sort_dicts=True)
    filename_literal = pformat(filenames, width=120, sort_dicts=True)
    return f'''"""Generated compatibility runtime for historical version modules.

Do not edit this file manually. Regenerate it with:
    python scripts/consolidate_versioned_modules.py --apply

The old source files are embedded verbatim and loaded lazily. This preserves
existing imports while keeping the maintained package surface in one place.
"""

from __future__ import annotations

import importlib.abc
import importlib.util
import linecache
import sys
from pathlib import Path
from types import ModuleType


_MODULE_SOURCES: dict[str, str] = {source_literal}
_MODULE_FILENAMES: dict[str, str] = {filename_literal}
_PACKAGE_DIR = Path(__file__).resolve().parent


class _VersionedModuleLoader(importlib.abc.Loader):
    def create_module(self, spec):
        return None

    def exec_module(self, module: ModuleType) -> None:
        source = _MODULE_SOURCES[module.__name__]
        filename = str(_PACKAGE_DIR / _MODULE_FILENAMES[module.__name__])
        module.__file__ = filename
        module.__package__ = module.__name__.rpartition(".")[0]
        module.__loader__ = self
        linecache.cache[filename] = (
            len(source),
            None,
            source.splitlines(keepends=True),
            filename,
        )
        exec(compile(source, filename, "exec"), module.__dict__)

    def get_source(self, fullname: str) -> str | None:
        return _MODULE_SOURCES.get(fullname)

    def get_filename(self, fullname: str) -> str:
        return str(_PACKAGE_DIR / _MODULE_FILENAMES[fullname])

    def is_package(self, fullname: str) -> bool:
        return False


class _VersionedModuleFinder(importlib.abc.MetaPathFinder):
    _loader = _VersionedModuleLoader()

    def find_spec(self, fullname: str, path=None, target=None):
        if fullname not in _MODULE_SOURCES:
            return None
        return importlib.util.spec_from_loader(
            fullname,
            self._loader,
            origin=self._loader.get_filename(fullname),
        )


_FINDER = _VersionedModuleFinder()


def install() -> None:
    if not any(isinstance(finder, _VersionedModuleFinder) for finder in sys.meta_path):
        sys.meta_path.insert(0, _FINDER)


def bundled_modules() -> tuple[str, ...]:
    return tuple(sorted(_MODULE_SOURCES))


__all__ = ["bundled_modules", "install"]
'''


def build_latest_facade() -> str:
    return '''"""Stable imports for the current OTA marketing diagnosis runtime.

New code should import from this module instead of a numbered ``*_vN`` module.
Historical module names continue to work through ``_versioned_runtime``.
"""

from __future__ import annotations

from marketing_diagnosis.data_v4 import normalize_dataset
from marketing_diagnosis.db_loader_v15 import load_database_dataset, load_mysql_dsn_dataset
from marketing_diagnosis.excel_loader_v2 import load_excel_package
from marketing_diagnosis.reporting_v2 import (
    build_ctrip_html,
    build_html,
    build_markdown,
    write_reports,
)
from marketing_diagnosis.rules_v5 import process


__all__ = [
    "build_ctrip_html",
    "build_html",
    "build_markdown",
    "load_database_dataset",
    "load_excel_package",
    "load_mysql_dsn_dataset",
    "normalize_dataset",
    "process",
    "write_reports",
]
'''


def update_package_init() -> None:
    text = INIT_PATH.read_text(encoding="utf-8") if INIT_PATH.exists() else ""
    if INIT_MARKER_START in text:
        return
    block = f'''\n\n{INIT_MARKER_START}\nfrom marketing_diagnosis._versioned_runtime import install as _install_versioned_runtime\n\n_install_versioned_runtime()\ndel _install_versioned_runtime\n{INIT_MARKER_END}\n'''
    INIT_PATH.write_text(text.rstrip() + block, encoding="utf-8")


def update_main_imports() -> None:
    text = MAIN_PATH.read_text(encoding="utf-8")
    old_lines = {
        "from marketing_diagnosis.data_v4 import normalize_dataset",
        "from marketing_diagnosis.excel_loader_v2 import load_excel_package",
        "from marketing_diagnosis.db_loader_v15 import load_database_dataset, load_mysql_dsn_dataset",
        "from marketing_diagnosis.reporting_v2 import write_reports",
        "from marketing_diagnosis.rules_v5 import process",
    }
    lines = text.splitlines()
    first_index = next((index for index, line in enumerate(lines) if line in old_lines), None)
    if first_index is None:
        return
    remaining = [line for line in lines if line not in old_lines]
    import_block = [
        "from marketing_diagnosis.latest import (",
        "    load_database_dataset,",
        "    load_excel_package,",
        "    load_mysql_dsn_dataset,",
        "    normalize_dataset,",
        "    process,",
        "    write_reports,",
        ")",
    ]
    remaining[first_index:first_index] = import_block
    MAIN_PATH.write_text("\n".join(remaining) + "\n", encoding="utf-8")


def write_manifest(records: list[dict[str, str]]) -> None:
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    rows = "\n".join(
        f"| `{record['file']}` | `{record['module']}` | `{record['sha256']}` |"
        for record in records
    )
    MANIFEST_PATH.write_text(
        "# Versioned module consolidation\n\n"
        "All numbered Python modules formerly stored as separate files under "
        "`marketing_diagnosis/` are embedded verbatim in "
        "`marketing_diagnosis/_versioned_runtime.py`. They are loaded lazily, so "
        "existing imports remain compatible without eagerly importing optional "
        "dependencies. New application code should import the stable API from "
        "`marketing_diagnosis.latest`.\n\n"
        "Git history remains the authoritative backup for every removed file.\n\n"
        "| Original file | Compatibility module | SHA-256 |\n"
        "|---|---|---|\n"
        f"{rows}\n",
        encoding="utf-8",
    )


def apply() -> int:
    paths = versioned_files()
    if not paths:
        if not BUNDLE_PATH.exists():
            raise SystemExit("No versioned modules found and no generated runtime exists")
        print("No separate versioned modules remain; consolidation is already applied")
        return 0

    sources: dict[str, str] = {}
    filenames: dict[str, str] = {}
    records: list[dict[str, str]] = []
    for path in paths:
        source = path.read_text(encoding="utf-8")
        name = module_name(path)
        sources[name] = source
        filenames[name] = path.name
        records.append({"file": path.name, "module": name, "sha256": digest(source)})

    BUNDLE_PATH.write_text(build_bundle(sources, filenames), encoding="utf-8")
    LATEST_PATH.write_text(build_latest_facade(), encoding="utf-8")
    update_package_init()
    update_main_imports()
    write_manifest(records)

    for path in paths:
        path.unlink()

    print(f"Bundled and removed {len(paths)} versioned modules")
    print(BUNDLE_PATH.relative_to(ROOT))
    print(LATEST_PATH.relative_to(ROOT))
    return 0


def check() -> int:
    remaining = versioned_files()
    failures: list[str] = []
    if remaining:
        failures.append("Separate versioned files remain: " + ", ".join(path.name for path in remaining))
    if not BUNDLE_PATH.exists():
        failures.append(f"Missing {BUNDLE_PATH.relative_to(ROOT)}")
    if not LATEST_PATH.exists():
        failures.append(f"Missing {LATEST_PATH.relative_to(ROOT)}")
    init_text = INIT_PATH.read_text(encoding="utf-8") if INIT_PATH.exists() else ""
    if INIT_MARKER_START not in init_text:
        failures.append("Package initializer does not install the versioned runtime")
    if failures:
        raise SystemExit("\n".join(failures))
    print("Versioned module consolidation check passed")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Consolidate numbered package modules safely")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--apply", action="store_true", help="Generate the runtime bundle and remove source copies")
    mode.add_argument("--check", action="store_true", help="Verify that consolidation is complete")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    return apply() if args.apply else check()


if __name__ == "__main__":
    raise SystemExit(main())
